### PR TITLE
docs: fix broken links

### LINKED ISSUE #425: docs: update all links to core.telegram.org/bots
The high-level docs have been reworked and many of your links are broken. This does not affect https://core.telegram.org/bots/api but likely most other links in all plugins and README files. Also the website should be checked for broken links.

### PR DESCRIPTION
**Pull request by roj1512**
Fixes #425

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks! Are these changes comprehensive?

**Comment by roj1512** [comment]
I fixed all links that matched `core.telegram.org/bots[^/]` and were broken. I also checked links matching `core.telegram.org/(?!bots)`, and none of them were broken.

**Comment by KnorpelSenf** [comment]
Fan

**Comment by KnorpelSenf** [comment]
tas

**Comment by KnorpelSenf** [comment]
tic

**Pull request merged**
