### PR TITLE
Export types CommandMiddleware, HearsMiddleware, etc

### LINKED ISSUE #100: feat: Expose narrowed context and middleware types
It would be neat to have a helper type for every method on `Composer` (where it makes sense), such as `OnContext`, `CommandContext`, etc.

Accordingly, we should have the matching middleware types: `OnMiddleware`, `CommandMiddleware`, etc.

Requested by @borodutch in https://t.me/grammyjs/23687

### PR DESCRIPTION
**Pull request by IlyaSemenov**
With this PR, it's possible to decompose command handlers into separate functions/modules.

Example:

```ts
// bot.ts
import { Bot, Context } from "grammy"

import { commands } from "./commands"

export type BotContext = Context & {}

const bot = new Bot<BotContext>()
bot.use(commands)
bot.use(/* ... */)
```

```ts
// commands/index.ts
import { Composer } from "grammy"

import { BotContext } from "../bot"

import { start_command } from "./start"
import { other_command } from "./other"

export const commands = new Composer<BotContext>()

commands.command("start", start_command)
commands.command("other", other_command)
// ...possibly 20 more commands
// no need to include all implementations in a single file or use dummy composers
```

```ts
// commands/start.ts
import { CommandMiddleware } from "grammy"

import { BotContext } from "../bot"

export const start_command: CommandMiddleware<BotContext> = async (ctx) => {
  console.log(ctx.match) // properly typed
}
```

Closes #100.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Thanks for working on #100! Would you mind exposing the other types in this PR, too?

**Comment by KnorpelSenf** [comment]
@IlyaSemenov could you have another look? I fixed it up.

**Review by KnightNiwrem — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
@add-contributors add @IlyaSemenov for code!

**Comment by KnorpelSenf** [comment]
@all-contributors add @IlyaSemenov for code!

**Pull request merged**
