### PR TITLE
docs: reformat contributors section

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Let's test a new layout. Review https://github.com/grammyjs/grammY/blob/compact-contribs/README.md.

Also, I did a podcast.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Is this any good?

**Review by roj1512 — APPROVED** [review]
LGTM. What about replacing that last line with

```
This project follows [all-contributors](https://github.com/all-contributors/all-contributors). Contributions of any kind are welcome!
```

?

**Comment by KnorpelSenf** [comment]
Great idea. Fixed that.

**Comment by KnorpelSenf** [comment]
Never seen a 120 lines docs change that was that easy

**Pull request merged**
