### PR TITLE
Revert "Use the new Telegram logo for the Bot API badge (#198)"

### PR DESCRIPTION
**Pull request by roj1512**
This reverts commit a4a17ec40cff663bd4eae9a6c3314fa9807c3769.

Reason for the revert:

- shields.io was updated and is using the new Telegram logo now (https://github.com/badges/shields/pull/7831).

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Comment by KnorpelSenf** [comment]
Have you considered signing your commits in the future?

I'll merge this now either way.

**Comment by KnorpelSenf** [comment]
You usually do this, right? 🤔

**Comment by roj1512** [comment]
I usually do what? 🤔

**Comment by KnorpelSenf** [comment]
Signing

**Pull request merged**
