### PR TITLE
fix: correct case usage for X-Telegram-Bot-Api-Secret-Token header in…

### PR DESCRIPTION
**Pull request by lejovaar7**
This update modifies the handling of the 'X-Telegram-Bot-Api-Secret-Token' header in both the synchronous and asynchronous AWS Lambda functions. 

In the previous implementation, the `SECRET_HEADER_LOWERCASE` constant was being used to retrieve the header from the event. This caused complications since AWS Lambda does not interpret headers in a case-insensitive way, leading to potential mismatches if the header was not supplied in the exact expected case.

With this fix, the `SECRET_HEADER` constant is used, which matches the exact casing of the 'X-Telegram-Bot-Api-Secret-Token' header as it appears in the event. This adjustment should eliminate any issues caused by case sensitivity.

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
LGTM

**Comment by KnorpelSenf** [comment]
@chrisandrewcl how come you used the lowercase version in #418? I didn't try this but it seems to me like the AWS docs imply that headers are not lowercased. Can you enlighten us?

**Comment by chrisandrewcl** [comment]
Expanding on what I said [here](https://github.com/grammyjs/grammY/pull/418#issuecomment-1567660003): while I have seen headers in the canonical form on lambdas before, I've not encountered telegram's secret header in canonical form while working with grammy for my project, just in its lowercase form. Given reports from other developers, it seems it doesn't mean it will always be lowercase, just that in this case it was lowercase. 

Similar reports highlighting this behavior: 
https://github.com/aws/aws-sam-cli/issues/3083#issuecomment-887632702 
https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-888800663

Given the inconsistencies, I was not confident opting for one or another but that was what ultimately was decided for the PR I submitted. 

To avoid this issue, you could consider normalizing the headers, checking for both formats or adding a note to the docs.

I am happy either way, since I ended up using the adapter just as a reference.

**Comment by KnorpelSenf** [comment]
Telegram always delivers headers with proper casing: https://github.com/tdlib/telegram-bot-api/blob/251589221708a8280ffcad32fcdc5348d014a6ae/telegram-bot-api/WebhookActor.cpp#L561

Since it seems like we all agree that AWS doesn't lowercase the headers (side note: why does any software mess with header casing even???), it seems to be the reasonable thing to merge this.

If we find a repro where this breaks anything, we can restart the discussion on the matter.

**Comment by KnorpelSenf** [comment]
CI will be fixed as soon as #465 is merged. The linting rules were updated, so we had to fix the code.

**Comment by KnorpelSenf** [comment]
@lejovaar7 please consider signing your commits in the future. I will overrule now and merge anyway, but we usually require this from contributors :)

**Comment by KnorpelSenf** [comment]
@all-contributors add @lejovaar7 for bug and code

**Comment by KnorpelSenf** [comment]
@all-contributors add @chrisandrewcl for review!

**Pull request merged**
