### PR TITLE
feat: Bot API 7.0

### PR DESCRIPTION
**Pull request by KnorpelSenf**
https://core.telegram.org/bots/api#december-29-2023

### CODE REVIEW

**Comment by niusia-ua** [comment]
Wow, what a big spec update. 🤯 Finally, bots can work with reactions. 🤩 In general, I would just like to express my respect for your quick work on the update. 👍 I anticipate a lot of work on our documentation. 🙃

**Comment by roj1512** [comment]
@all-contributors @AbbassAlmusawi for bug

**Comment by roj1512** [comment]
@all-contributors add @AbbassAlmusawi for bug

**Comment by KnorpelSenf** [comment]
> I anticipate a lot of work on our documentation. 🙃

It will not be a lot, but there will definitely be some. I am going to get started with that now.

**Comment by KnorpelSenf** [comment]
@niusia-ua check out https://github.com/grammyjs/website/pull/971

**Review by roziscoding — APPROVED** [review]

**Pull request merged**
