### PR TITLE
feat: add customizable fetch function to ApiClientOptions

### PR DESCRIPTION
**Pull request by IKatsuba**
This pull request introduces a new feature to the `ApiClient` class in `src/core/client.ts` to allow custom `fetch` functions. This enables more flexibility in making HTTP requests, especially in different environments like Node.js and Deno.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Can you explain a use case for a custom fetch function?

**Comment by IKatsuba** [comment]
This PR gives a possibility to use native `fetch` for Node.js environments instead of `node-fetch`

**Comment by KnorpelSenf** [comment]
That's a great point. I might remove this again for 2.0 when we migrate to native fetch, we'll see. Either way, I'll open an issue about it first.

**Review by KnorpelSenf — APPROVED** [review]
LGTM. Thanks!

**Comment by BilagoNet** [comment]
After update with big extimol i.e. 1.31.1 cloudflare workers stopped working, I think it was because fetch was added to this ApiClientOptions.

Error log in Cloidflare workers:
TypeError: Illegal invocation: function called with incorrect `this` reference.

image

**Comment by KnorpelSenf** [comment]
@IKatsuba do you have time to fix up your changes?

**Comment by IKatsuba** [comment]
> @IKatsuba do you have time to fix up your changes?

I will research it during the day today

**Comment by KnorpelSenf** [comment]
> > @IKatsuba do you have time to fix up your changes?
> 
> I will research it during the day today

Epic, thank you!

**Pull request merged**
