### PR TITLE
feat: JSR compatibility

### LINKED ISSUE #559: Publish `grammY` to JSR registry
1. GitHub Action: <https://jsr.io/docs/publishing-packages#publishing-from-github-actions>
2. Migrating Deno modules from /x to JSR: <https://jsr.io/docs/migrate-x-to-jsr>

You can use `npm` or `deno` to get packages from JSR.

### PR DESCRIPTION
**Pull request by niusia-ua**
With this PR, we are starting to work on migrating grammY and its ecosystem to the JSR registry.

Specifically, this PR resolves some of the [type issues](https://jsr.io/docs/about-slow-types) that arise due to JSR's restrictions.
Please review all changes carefully and test them on your bots.
In general, these changes shouldn't affect the logic of grammY, but it's worth making sure.

For example, the evaluation result has been improved from 47% to 76% (see screenshot).
Also, according to JSR, this should have improved the speed of code compilation.
The remaining scores are related to the package documentation.

This is just the beginning of the work.
In general, the migration to JSR should be fully completed with the release of grammY 2.0.
The second version will solve many of the existing problems, as well as move the code from a platform-specific approach to code compilation to capability-driven code behaviour.
This will allow us to fully rely on JSR to support multiple platforms.

You can test the build locally.
To do this, first run JSR on your machine [as instructed](https://github.com/jsr-io/jsr?tab=readme-ov-file#getting-started-entire-stack).
Then publish the grammY package using `JSR_URL=http://jsr.test deno publish`.
The package will be available at <http://jsr.test/@grammyjs/grammy>, and the NPM build at <http://npm.jsr.test/@jsr/grammyjs__grammy>.
In the metafile of the NPM build, you can find a link to an archive that you can download and unzip to view its contents.
Such a build is suitable for publishing to NPM, except that it needs to be edited and repackaged a bit.

Screenshot from 2024-08-24 09-45-31

Closes #559.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Closing this was accidental

**Comment by niusia-ua** [comment]
Yeah, please take care of this yourself.
Sorry, I haven't had enough time and passion to work on this lately. And now there are conflicts, so extra work is required to pretify everything.

**Comment by KnorpelSenf** [comment]
No worries. Will do!

**Comment by KnorpelSenf** [comment]
Done: https://jsr.io/@grammyjs/grammy@2.0.0-beta.0

**Pull request closed without merging**
