### PR TITLE
feat: add support for Bot API 6.6

### PR DESCRIPTION
**Pull request by KnorpelSenf**
https://core.telegram.org/bots/api#march-9-2023

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Main thing to review are the newly introduced method signatures on the `Api` class.

**Comment by roj1512** [comment]
- [ ]    Added the ability to set different bot descriptions for different user languages using the method [setMyDescription](https://core.telegram.org/bots/api#setmydescription).
 - [ ]   Added the ability to get the current bot description in the given language as the class [BotDescription](https://core.telegram.org/bots/api#botdescription) using the method [getMyDescription](https://core.telegram.org/bots/api#getmydescription).
 - [ ]   Added the ability to set different bot short descriptions for different user languages using the method [setMyShortDescription](https://core.telegram.org/bots/api#setmyshortdescription).
 - [ ]   Added the ability to get the current bot short description in the given language as the class [BotShortDescription](https://core.telegram.org/bots/api#botshortdescription) using the method [getMyShortDescription](https://core.telegram.org/bots/api#getmyshortdescription).
 - [ ]   Added the parameter emoji to the method [sendSticker](https://core.telegram.org/bots/api#sendsticker) to specify an emoji for just uploaded stickers.
 - [ ]   Added support for the creation of custom emoji sticker sets in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
 - [ ]   Added the parameter needs_repainting to the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) to automatically change the color of emoji based on context (e.g., use text color in messages, accent color in statuses, etc.).
 - [ ]   Added the field needs_repainting to the class [Sticker](https://core.telegram.org/bots/api#sticker).
 - [ ]   Replaced the parameters png_sticker, tgs_sticker, webm_sticker, emojis and mask_postion in the method [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset) with the parameter sticker of the type [InputSticker](https://core.telegram.org/bots/api#inputsticker).
 - [ ]   Added support for the creation of sticker sets with multiple initial stickers in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) by replacing the parameters png_sticker, tgs_sticker, webm_sticker, emojis and mask_postion with the parameters stickers and sticker_format.
 - [ ]   Added support for .WEBP files in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) and [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset).
 - [ ]   Added support for .WEBP, .TGS, and .WEBM files in [uploadStickerFile](https://core.telegram.org/bots/api#uploadstickerfile) by replacing the parameter png_sticker in the method [uploadStickerFile](https://core.telegram.org/bots/api#uploadstickerfile) with the parameters sticker and sticker_format.
 - [ ]   Added the ability to specify search keywords for stickers added to sticker sets.
 - [ ]   Added the method [setCustomEmojiStickerSetThumbnail](https://core.telegram.org/bots/api#setcustomemojistickersetthumbnail) for editing the thumbnail of custom emoji sticker sets created by the bot.
 - [ ]   Added the method [setStickerSetTitle](https://core.telegram.org/bots/api#setstickersettitle) for editing the title of sticker sets created by the bot.
 - [ ]   Added the method [deleteStickerSet](https://core.telegram.org/bots/api#deletestickerset) for complete deletion of a given sticker set that was created by the bot.
 - [ ]   Added the method [setStickerEmojiList](https://core.telegram.org/bots/api#setstickeremojilist) for changing the list of emoji associated with a sticker.
 - [ ]   Added the method [setStickerKeywords](https://core.telegram.org/bots/api#setstickerkeywords) for changing the search keywords assigned to a sticker.
 - [ ]   Added the method [setStickerMaskPosition](https://core.telegram.org/bots/api#setstickermaskposition) for changing the [mask position](https://core.telegram.org/bots/api#maskposition) of a mask sticker.
 - [ ]   Renamed the field thumb in the classes [Animation](https://core.telegram.org/bots/api#animation), [Audio](https://core.telegram.org/bots/api#audio), [Document](https://core.telegram.org/bots/api#document), [Sticker](https://core.telegram.org/bots/api#sticker), [Video](https://core.telegram.org/bots/api#video), [VideoNote](https://core.telegram.org/bots/api#videonote), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaAudio](https://core.telegram.org/bots/api#inputmediaaudio), [InputMediaDocument](https://core.telegram.org/bots/api#inputmediadocument), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [StickerSet](https://core.telegram.org/bots/api#stickerset) to thumbnail.
 - [ ]   Renamed the parameter thumb in the methods [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote) to thumbnail.
 - [ ]   Renamed the method setStickerSetThumb to [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail) and its parameter thumb to thumbnail.
 - [ ]   Renamed the fields thumb_url, thumb_width, and thumb_height in the classes [InlineQueryResultArticle](https://core.telegram.org/bots/api#inlinequeryresultarticle), [InlineQueryResultContact](https://core.telegram.org/bots/api#inlinequeryresultcontact), [InlineQueryResultDocument](https://core.telegram.org/bots/api#inlinequeryresultdocument), [InlineQueryResultLocation](https://core.telegram.org/bots/api#inlinequeryresultlocation), and [InlineQueryResultVenue](https://core.telegram.org/bots/api#inlinequeryresultvenue) to thumbnail_url, thumbnail_width, and thumbnail_height respectively.
 - [ ]   Renamed the field thumb_url in the classes [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto) and [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo) to thumbnail_url.
 - [ ]   Renamed the fields thumb_url and thumb_mime_type in the classes [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), and [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif) to thumbnail_url and thumbnail_mime_type respectively.

**Comment by KnorpelSenf** [comment]
nice

**Review by roj1512 — COMMENTED** [review]
The second parameters of the methods [`setCustomEmojiStickerSetThumbnail`](https://core.telegram.org/bots/api#setcustomemojistickersetthumbnail) and [`setStickerMaskPosition`](https://core.telegram.org/bots/api#setstickermaskposition) are marked optional in Telegram docs, while they are required here.

**Comment by KnorpelSenf** [comment]
They are required because if one wants to remove the thumbnail (use the first), then which code do you find more readable?

```ts
await ctx.api.setCustomEmojiStickerSetThumbnail(name)
```
or

```ts
await ctx.api.setCustomEmojiStickerSetThumbnail(name, undefined)
```
?

**Review by roj1512 — APPROVED** [review]
LGTM. All the new signatures are correct.

**Pull request merged**
