### PR TITLE
docs: fix links

### PR DESCRIPTION
**Pull request by dcdunkan**

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Great changes but please revert the unrelated whitespace changes to the source code

**Comment by dcdunkan** [comment]
https://github.com/grammyjs/grammY/blob/8ebf31cbbafc784eb9c0c6517ea297d97e2cbe9e/src/core/api.ts#L2366

Here the anchors are outdated and can be updated to video-requirements and animation-requirements. Should I include those as well? Since those docs are from the Bot API docs itself, I didn't know what to do.

**Comment by dcdunkan** [comment]
> Great changes but please revert the unrelated whitespace changes to the source code

My bad. Fixing them...

**Comment by KnorpelSenf** [comment]
> https://github.com/grammyjs/grammY/blob/8ebf31cbbafc784eb9c0c6517ea297d97e2cbe9e/src/core/api.ts#L2366
> 
> Here the anchors are outdated and can be updated to video-requirements and animation-requirements. Should I include those as well? Since those docs are from the Bot API docs itself, I didn't know what to do.

Are they also outdated in the official Telegram docs?

**Comment by dcdunkan** [comment]
Yes

**Comment by dcdunkan** [comment]
Wait

**Comment by KnorpelSenf** [comment]
Then we are going to keep broken links in our documentation, as well, until Telegram fixes the issue. This is going to happen soon.

**Review by KnorpelSenf — APPROVED** [review]
Thank you so much!

**Comment by KnorpelSenf** [comment]
@dcdunkan are you planning on opening similar PQs to the other repositories in the organisation?

**Comment by dcdunkan** [comment]
Yes, in my free time.

**Comment by KnorpelSenf** [comment]
We can fix it now, it was already done in https://github.com/grammyjs/types/commit/2987b30c6f652370ae9a8d965f0406967f9ca6db for the types

**Pull request merged**
