### PR TITLE
fix: case insensitive bot commands

### PR DESCRIPTION
**Pull request by shaunnope**
## Issue
Bot usernames are not case sensitive. Hence, commands such as `/foo@this_bot`, `/foo@this_Bot`, and `/foo@tHis_bOt` would all be sent to a bot with username `@this_bot`.

The existing implementation for bot command checking _is_ case sensitive, causing bot commands with non-standard username capitalisation to not be handled by a grammY bot.

### Example
```javascript
import { Bot } from "grammy";

const bot = new Bot("<telegram token>");

bot.command('foo', ctx => ctx.reply("bar"))

// catch unhandled messages
bot.use(ctx => ctx.chat && ctx.reply("unhandled"))

bot.start();
```

## Proposed Solution
Convert both `atTarget` and `ctx.me.username` to lower case before comparison.

## Notes
I note the intention to configure case insensitivity using the `commands` plugin, as mentioned in #108 and #275. However, I believe this is a separate issue, since bot usernames are inherently case insensitive.

### CODE REVIEW

**Comment by roj1512** [comment]
Possibly relatable: https://github.com/grammyjs/grammY/issues/275

**Review by KnorpelSenf — APPROVED** [review]
LGTM, thanks!

**Comment by KnorpelSenf** [comment]
@all-contributors add @shaunnope for bug and code!

**Comment by KnorpelSenf** [comment]
Please fix CI

**Comment by KnorpelSenf** [comment]
Thanks. We usually require all contributors to sign their commits. I will ignore that now and merge anyway, but please consider setting this up for future contributions :) (and cuz it's good practice)

**Comment by shaunnope** [comment]
> Thanks. We usually require all contributors to sign their commits. I will ignore that now and merge anyway, but please consider setting this up for future contributions :) (and cuz it's good practice)

Oh thanks! I'll bear that in mind :)

**Pull request merged**
