### PR TITLE
Add Deno shield

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
If its style not matching with the other badges is a problem, we can modify the styles of the shieldsio badges. The style of the Deno shield is not modifiable.

**Comment by KnorpelSenf** [comment]
Yes, please align the design before we merge this.

**Comment by roj1512** [comment]
@KnorpelSenf I’ve changed the colors of the shieldsio badges, they look similar to the Deno shield now, except for a small unmodifiable white gradient on the message part of them, which is less noticable. You decide :)

**Comment by roj1512** [comment]
@KnorpelSenf How are they looking now?

**Comment by EdJoPaTo** [comment]
The Deno shield has no color gradient, the others have.

image

**Review by KnorpelSenf — APPROVED** [review]
LGTM. Thanks! Good idea :)

**Comment by KnorpelSenf** [comment]
In fact, `img.shields.io` allows us to use any logo, text, and design. If we want, we could switch back to the old designs, and simply avoid pulling in the Deno shield from `deno.com`. What do you think?

**Comment by HeeroML** [comment]
👍Am Di., 10.Mai.2022 um 12:26, KnorpelSenf ***@***.***> schrieb:  
In fact, img.shields.io allows us to use any logo, text, and design. If we want, we could switch back to the old designs, and simply avoid pulling in the Deno shield from deno.com. What do you think?

**Comment by roj1512** [comment]
@KnorpelSenf If you prefer, we can remove the version part on the npm badge and do all of the work with shieldsio.

**Comment by KnorpelSenf** [comment]
I think it makes a lot of sense to have the same version on both shields. That way, it's very clear how we publish the identical versions for both runtimes.

**Comment by roj1512** [comment]
That way you should use the Deno shield. Because there won't be a way to add the version to a manually made shieldsio badge.

**Comment by EdJoPaTo** [comment]
Alternatively… isnt shields.io open source? :smirk:

**Comment by KnorpelSenf** [comment]
You want to fork and add the feature we need?

**Comment by roj1512** [comment]
@EdJoPaTo Does that mean you will host an instance for us, or do you mean to PR this feature? They don’t accept PRs easily. Reference: https://github.com/badges/shields/pull/7831

**Comment by KnorpelSenf** [comment]
It seems like there is progress on the linked PQ now.

**Comment by roj1512** [comment]
Yes, happily.

**Comment by KnorpelSenf** [comment]
@roj1512 this PQ modified the section controlled by all-contributors. The styling will be overwritten whenever a new contributor gets listed in the README.

Should we maybe switch to the automatically generated badge the is described in https://github.com/all-contributors/all-contributors/issues/406?

**Pull request merged**
