### PR TITLE
chore: Rename `Andrey Zontov` to `Andrii Zontov`

### PR DESCRIPTION
**Pull request by LWJerri**
In Ukraine, we use `Andrii` instead of `Andrey`.

### CODE REVIEW

**Review by KnorpelSenf — COMMENTED** [review]
Did you run `deno task contribs generate` again?

**Comment by LWJerri** [comment]
> Did you run `deno task contribs generate` again?

Yes, but nothing was changed.

**Review by KnorpelSenf — APPROVED** [review]
Awesome, thanks

**Comment by KnorpelSenf** [comment]
@LWJerri remember to sign your commits again :)

**Pull request merged**
