### PR TITLE
Add `readAll` and internal data access to memory session

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Title says it all. Requested in https://t.me/grammyjs_ru/101

### CODE REVIEW

**Comment by Satont** [comment]
It looks cool.

In the same discussion, we had the idea of adding a method to get all the sessions. Can we add this in the same PR?

**Comment by KnorpelSenf** [comment]
Yes, we can add that.

I'm also thinking about allowing

```ts
for await (const data of ctx.session) {
  // handle session data of user
}
```

which would effectively allow you to enumerate all sessions.

This would be optional to implement for storage adapters. Hence, it is a non-breaking change. Storage adapters that do not support this will simply throw an error when this is attempted.

**Comment by KnorpelSenf** [comment]
@Satont please review.

**Comment by Satont** [comment]
Looking good, thank you. 👍

**Comment by KnorpelSenf** [comment]
Taking that as an accepted review, merging.

**Pull request merged**
