### PR TITLE
Check for Deno api property not exposed by Deno deploy

### PR DESCRIPTION
**Pull request by jokasimr**
This might not be the most 'gentle' way to check for permissions. :D

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Does this even compile on Deno Deploy? I thought that `Deno.permissions` is not available?

**Comment by jokasimr** [comment]
I think it compiles, `Deno.permissions` just evaluates to `undefined` in that runtime.

**Comment by jokasimr** [comment]
Here is a small test referencing the Dino.permissions property in the deploy runtime: 
 https://github.com/jokasimr/sf2-collective/blob/bot/bot/test.js

It runs here:
https://large-chicken-55.deno.dev/

And compiles :)

**Comment by KnorpelSenf** [comment]
Amazing, that is certainly a change to the service then. This makes fixing the problem much easier. Could you check out #17?

**Pull request closed without merging**
