### PR TITLE
support `nhttp` for webhook handler

### PR DESCRIPTION
**Pull request by shevernitskiy**
This PR adds support for [nhttp](https://nhttp.deno.dev/) for webhook handler.

### CODE REVIEW

**Comment by shevernitskiy** [comment]
> Does this library support returning responses from a `Response` instance?

Handler signature assume the only `RequestEvent` as arg. `Response` object could be returned as well as plenty other types.

**Comment by roj1512** [comment]
We already have a `Request` adapter. Does that suffice?

**Comment by shevernitskiy** [comment]
> We already have a `Request`-`Response` adapter. Does that suffice?

nhttp `RequestEvent` has a source request object, but with consumed body. Also it has `newRequest` - the clone of the original one with no consumed body (this one match for basic Req => Res). But it is a clone - no good for perf and memory, obviously. So thats why I made this PR.

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Comment by KnorpelSenf** [comment]
@all-contributors add @shevernitskiy for their code

**Comment by KnorpelSenf** [comment]
@shevernitskiy we usually require all contributors to sign their commits. I overruled this now and merged anyway, but please consider signing your commits in the future.

**Pull request merged**
