### PR TITLE
Add `Deno.serveHttp` adapter for `webhookCallback`

### PR DESCRIPTION
**Pull request by rojserbest**
Example usage:

```ts
import {
  Bot,
  webhookCallback,
} from "https://raw.githubusercontent.com/rojserbest/grammY/main/src/mod.ts";

const bot = new Bot('') // <-- your bot token here;
const handleUpdate = webhookCallback(bot, "serveHttp");

bot.command("start", (ctx) => ctx.reply("Hi!"));

const server = Deno.listen({ port: 8000 });

for await (const conn of server) {
  serveHttp(conn);
}

async function serveHttp(conn: Deno.Conn) {
  const httpConn = Deno.serveHttp(conn);

  for await (const requestEvent of httpConn) {
    if (requestEvent.request.method == "POST") {
      await handleUpdate(requestEvent);
    }

    await requestEvent.respondWith(new Response(undefined, { status: 200 }));
  }
}
```

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
This will have to wait until #61 is merged, which will largely refactor how adapters are organised.

**Comment by rojserbest** [comment]
Yeah, nice PR. But what will be done to `std/http`? 🤔

**Comment by rojserbest** [comment]
Also, I guess that PR lets defining custom adapters too.

**Comment by KnorpelSenf** [comment]
The API I desire is to have a bunch of framework adapters supported out of the box and accessible via simple string identifiers. If you're using some esoteric stuff that grammY doesn't support, you can still pass your own definition. I am still waiting for feedback on this.

> what will be done to `std/http`?

What do you mean?

**Comment by rojserbest** [comment]
Feedback on how adapters should work?

**Comment by rojserbest** [comment]
> What do you mean?

I mean: will we support both `serveHttp` and [`std/http`](https://deno.land/std@0.115.1/http), separately?

**Comment by KnorpelSenf** [comment]
Feedback on my suggestion that it's superfluous to expose 20 framework adapters when all you can do with them is to pass them to the same function. They shouldn't be accessible as objects.

Continue this here: https://github.com/grammyjs/grammY/pull/61#discussion_r749303091

**Comment by KnorpelSenf** [comment]
> > What do you mean?
> 
> I mean: will we support both `serveHttp` and [`std/http`](https://deno.land/std@0.115.1/http), separately?

They're different abstractions. Why not?

**Comment by KnorpelSenf** [comment]
Please resolve the conflicts.

**Comment by rojserbest** [comment]
Done!

**Comment by rojserbest** [comment]
Sorry, I don't understand you. What the "this" in "this can be used"?

**Comment by KnorpelSenf** [comment]
Sorry for being ambiguous. Does this work?

```ts
import {
  Bot,
  webhookCallback,
} from "https://raw.githubusercontent.com/rojserbest/grammY/main/src/mod.ts";

const bot = new Bot('') // <-- your bot token here;
const handleUpdate = webhookCallback(bot, "serveHttp");

bot.command("start", (ctx) => ctx.reply("Hi!"));

const server = Deno.listen({ port: 8000 });

for await (const conn of server) {
  serveHttp(conn);
}

async function serveHttp(conn: Deno.Conn) {
  const httpConn = Deno.serveHttp(conn);

  for await (const requestEvent of httpConn) {
    if (requestEvent.request.method == "POST") {
      await handleUpdate(requestEvent);
    }
  }
}
```

**Comment by rojserbest** [comment]
Sure it does. You can even test it fast using Deno deploy.

**Comment by KnorpelSenf** [comment]
So there's no reason you called `await requestEvent.respondWith(new Response(undefined, { status: 200 }));`?

**Review by KnorpelSenf — APPROVED** [review]
LGTM

**Comment by KnorpelSenf** [comment]
@all-contributors add @rojserbest for code

**Comment by rojserbest** [comment]
> So there's no reason you called `await requestEvent.respondWith(new Response(undefined, { status: 200 }));`?

There was a reason, but when I edited my code wrongly some days ago, I removed the lines where you would see the reason. Fixed now. See it again to see what I meant by that.

**Comment by KnorpelSenf** [comment]
But now you're still responding to the request twice, aren't your? Once inside the adapter, and once afterwards in the try block

**Comment by rojserbest** [comment]
That line would make sense if someone sent a get request, so they would know that the server is running. After all, it's just an example and you can remove that line and it will still work.

**Comment by KnorpelSenf** [comment]
It will also run on POST requests

**Comment by KnorpelSenf** [comment]
Miss it's good

**Comment by rojserbest** [comment]
My bad, I'm lazy.

**Comment by KnorpelSenf** [comment]
No worries, just wanted to know if I understood it correctly

**Pull request merged**
