### PR TITLE
feat: add SvelteKit adapter

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Adds support for https://kit.svelte.dev/

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
I assume that `response` and `unauthorized` will also fail

**Comment by ak4zh** [comment]
I think we need to create `new Response()` similar to `std/http`.

**Comment by KnorpelSenf** [comment]
@KnightNiwrem since you already have a setup running, do you want to fix this up?

**Comment by ak4zh** [comment]
This seems to work, I copied the missing parts from stdHttp adapter

```js
const sveltekit = (event: any) => {
    let resolveResponse: (res: Response) => void;
    return {
        update: Promise.resolve(event.request.json()),
        header: event.request.headers[SECRET_HEADER],
        end: () => {
            if (resolveResponse) resolveResponse(new Response());
        },
        respond: (json: string) => {
            if (resolveResponse) {
                const res = new Response(json, {
                    headers: { "Content-Type": "application/json" },
                });
                resolveResponse(res);
            }
        },
        unauthorized: () => {
            if (resolveResponse) {
                const res = new Response("secret token is wrong", {
                    status: 401,
                });
                resolveResponse(res);
            }
        },
        handlerReturn: new Promise((resolve) => {
            resolveResponse = resolve;
        }),
    }
};
```

**Comment by KnightNiwrem** [comment]
> This seems to work, I copied the missing parts from stdHttp adapter
> 
> ```js
> const sveltekit = (event: any) => {
>     let resolveResponse: (res: Response) => void;
>     return {
>         update: Promise.resolve(event.request.json()),
>         header: event.request.headers[SECRET_HEADER],
>         end: () => {
>             if (resolveResponse) resolveResponse(new Response());
>         },
>         respond: (json: string) => {
>             if (resolveResponse) {
>                 const res = new Response(json, {
>                     headers: { "Content-Type": "application/json" },
>                 });
>                 resolveResponse(res);
>             }
>         },
>         unauthorized: () => {
>             if (resolveResponse) {
>                 const res = new Response("secret token is wrong", {
>                     status: 401,
>                 });
>                 resolveResponse(res);
>             }
>         },
>         handlerReturn: new Promise((resolve) => {
>             resolveResponse = resolve;
>         }),
>     }
> };
> ```

Would `const sveltekit = ({ request: Request }) => {` be a better option, since we don't intend to use anything else in `event` other than `event.request`.

**Comment by KnorpelSenf** [comment]
That code doesn't parse, but yes, it'd be great to have the type safety and do `event: { request: Request }` or `{ request }: { request: Request }`, which would also make clear what we depend on.

**Comment by KnorpelSenf** [comment]
I'll update the code in a sec

**Comment by KnightNiwrem** [comment]
Screen Shot 2022-12-11 at 11 25 09 AM

Verified

**Review by KnightNiwrem — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
@all-contributors add @ak4zh for review

**Pull request merged**
