### PR TITLE
Don't automate the badge for All Contributors

### PR DESCRIPTION
**Pull request by roj1512**
- This maintains our custom styles and makes the style of the badge for All Contributors consistent with the others.
- Related: https://github.com/grammyjs/grammY/pull/197#issuecomment-1126995485

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Did you test this?

**Comment by roj1512** [comment]
Do you mean testing if the badge works or testing to know if it is persisting after you send an All Contributors update?

If you mean the badge, you can preview it here: https://github.com/grammyjs/grammY/tree/all-contributors

**Comment by KnorpelSenf** [comment]
I meant running the tooling and making sure things aren't overwritten.

**Review by KnorpelSenf — APPROVED** [review]
I tested it now, it works. Thanks!

**Pull request merged**
