### PR TITLE
fix(web): do not rely on ReadableStream.from

### LINKED ISSUE #491: bug: passing blob to `new InputFile()` lead to this error on **Vercel Edge Runtime**:
Since this change, passing blob to `new InputFile()` lead to this error on **Vercel Edge Runtime**:

`TypeError: ReadableStream.from is not a function`

Example code:

```js
const response = await fetch(url, {headers, method, body});

const file = new InputFile(await response.blob(), filename);

await ctx.replyWithDocument(file);
```

Снимок экрана 2023-10-07 в 19 12 07

_Originally posted by @PonomareVlad in https://github.com/grammyjs/grammY/pull/484#discussion_r1349527155_

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Fixes #491

### CODE REVIEW

**Review by MKRhere — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
Apparently CFW does not support `new ReadableStream`. Why???

**Comment by KnorpelSenf** [comment]
https://developers.cloudflare.com/workers/runtime-apis/streams/readablestream/

**Comment by roj1512** [comment]
> Apparently CFW does not support new ReadableStream. Why???

Because they didn’t know of @KnightNiwrem when they decided to not support it.

**Review by PonomareVlad — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
It does support it, but you have to set a flag: https://github.com/grammyjs/grammY/pull/493#issuecomment-1751945395

**Pull request merged**
