### PR TITLE
Add adapter for AdonisJS

### PR DESCRIPTION
**Pull request by watzon**

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Thanks for this contribution! I'll be happy to merge this after the compilation and formatting errors are fixed :)

**Comment by KnorpelSenf** [comment]
@watzon are you still interested in fixing this up?

**Comment by watzon** [comment]
@KnorpelSenf yep, just need to get some time to do it

**Comment by KnorpelSenf** [comment]
Awesome, take your time :)

**Comment by KnorpelSenf** [comment]
#257 created conflicts, but I'm sure they won't be too hard to resolve.

**Comment by KnorpelSenf** [comment]
Closing because of inactivity. Feel free to repoen if you want to pick it up again.

**Pull request closed without merging**
