### PR TITLE
chore: make deno the default formatter for VSCode

### PR DESCRIPTION
**Pull request by roziscoding**
as discussed in https://grammyjs.t.me/73886

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Can we apply this to linting and testing, too?

**Comment by KnorpelSenf** [comment]
> we should make deno the default overall formatter, as opposed to only applying it to typescript

Very good point, please go ahead

**Comment by Loskir** [comment]
Should we limit it to specific file types?

**Comment by KnorpelSenf** [comment]
We actually format everything with Deno, so I don't see how that would help

**Comment by KnorpelSenf** [comment]
@all-contributors add @roziscoding for infra and ideas :)

**Pull request merged**
