### PR TITLE
feat: filter stickers by type

### LINKED ISSUE #334: Filter by document types
I am still trying to understand the grammy `filter.ts` to figure out how to handle the suggestion I am going to make.

Just putting it out there to know if you guys will be interested in adding more filter options like below or if it's out of scope for the project.

```
const DOCUMENT_KEYS = {
	'apk': {},
	'doc': {},
	'docx': {},
	'exe': {},
	'gif': {},
	'jpg': {},
	'pdf': {},
	'py': {},
	'svg': {},
	'txt': {},
	'tarz': {},
	'wav': {},
	'xml': {},
	'zip': {}
}

const STICKER_KEYS = {
	'animated': {},
	'static': {},
	'video': {},
	'premium': {}
}

// L2
const EDITABLE_MESSAGE_KEYS = {
	text: {},
	animation: {},
	audio: {},
	document: DOCUMENT_KEYS,
        ....
}

const COMMON_MESSAGE_KEYS = {
	...EDITABLE_MESSAGE_KEYS,
	sticker: STICKER_KEYS,
        ...
}
```

### PR DESCRIPTION
**Pull request by ak4zh**
Closes #334

### CODE REVIEW

**Comment by ak4zh** [comment]
There should be another one `is_static` but it is not available in [sticker object](https://core.telegram.org/bots/api#sticker).
So not sure if it's possible.

Maybe we can add `is_static` in the sticker object internally when `is_animation` and `is_video` both are false.

**Comment by KnorpelSenf** [comment]
This is not possible. This will break if a new sticker type is added. People can already filter for static stickers using `bot.drop` in combination with the filter queries introduced in this pull request :)

**Comment by ak4zh** [comment]
Correct, `bot.drop` does make sense.
So it seems complete.

**Review by KnorpelSenf — APPROVED** [review]
Thank you so much!

**Comment by KnorpelSenf** [comment]
@all-contributors add @ak4zh for this idea and the code contribution!

**Comment by KnorpelSenf** [comment]
@ak4zh we usually require all contributors to sign their commits, please consider setting this up in the future :)

I will merge anyway now.

**Pull request merged**
