### PR TITLE
feat: add web-specific code

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Adds code that is specific to the web. This means:
- the supported web frameworks differ
- the supported input file types differ
- there is no need for TLA because the only time we need this is when running inside Deno and have to query for permission to read the DEBUG env var

This build should run in all evergreen browsers as well as Cloudflare Workers and other edge runtimes.

### CODE REVIEW

**Comment by roziscoding** [comment]
I'm guessing we have some non-shared dependencies then?
I'll wait until later™ for the explanation to review further, but I see no red flags right now

**Comment by roziscoding** [comment]
Oh. I see. No TLA now
But it being a web version, do we need to get rid of TLA?

**Comment by KnorpelSenf** [comment]
CFW

**Comment by KnorpelSenf** [comment]
@roziscoding please take another look

**Review by roziscoding — APPROVED** [review]
Seems about right :)

**Comment by roziscoding** [comment]
Wait
The changes in package.json are missing

**Comment by KnorpelSenf** [comment]
I'm targeting your PQ

**Comment by KnorpelSenf** [comment]
This isn't supposed to be merged into main

**Comment by roziscoding** [comment]
Oh
Then let's f'ing go :D

**Comment by KnorpelSenf** [comment]
*not directly

**Comment by roziscoding** [comment]
Can I do the honors then?

**Comment by KnorpelSenf** [comment]
Absolutely, go ahead 🤓

**Pull request merged**
