### PR TITLE
chore: remove npm scripts not required for GitHub installs

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Regarding https://github.com/grammyjs/grammY/pull/224#discussion_r884245894. Is this what you meant?

### CODE REVIEW

**Comment by Satont** [comment]
> Regarding [#224 (comment)](https://github.com/grammyjs/grammY/pull/224#discussion_r884245894). Is this what you meant?

Yes.

**Comment by KnorpelSenf** [comment]
> > Regarding [#224 (comment)](https://github.com/grammyjs/grammY/pull/224#discussion_r884245894). Is this what you meant?
> 
> Yes.

Alright, will merge after approval.

**Review by roj1512 — APPROVED** [review]

**Review by Satont — APPROVED** [review]
LGTM.

**Comment by roj1512** [comment]
@KnorpelSenf Yes, this was what I meant.

**Comment by KnorpelSenf** [comment]
Thanks!

**Pull request merged**
