### PR TITLE
fix: `ctx.chat` for callback queries

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Potential fix for https://t.me/grammyjs/228143

### CODE REVIEW

**Review by KnightNiwrem — APPROVED** [review]

**Comment by KnightNiwrem** [comment]
To also fix in another PQ with similar "patterns" of code:

`msgId: [Shortcuts<U>["msg"]] extends [object] ? number`
Screenshot 2024-04-09 at 12 42 17 PM

`businessConnectionId: [Shortcuts<U>["msg"]] extends [object] ? string | undefined`
Screenshot 2024-04-09 at 12 44 24 PM

**Comment by KnorpelSenf** [comment]
Right, I'll fix those

**Comment by KnightNiwrem** [comment]
All fixes for https://github.com/grammyjs/grammY/pull/555#issuecomment-2044140513 has been verified.

Some regression bugs have surfaced.
Screenshot 2024-04-20 at 3 14 44 PM
Screenshot 2024-04-20 at 3 14 38 PM
Screenshot 2024-04-20 at 3 11 26 PM

**Comment by KnorpelSenf** [comment]
> All fixes for [#555 (comment)](https://github.com/grammyjs/grammY/pull/555#issuecomment-2044140513) has been verified.

Awesome!

> Some regression bugs have surfaced. Screenshot 2024-04-20 at 3 14 44 PM Screenshot 2024-04-20 at 3 14 38 PM

Those two are invalid. There is no such field as `id` on a message, so the error is correct. You might have meant `message_id` which works correctly.

> Screenshot 2024-04-20 at 3 11 26 PM

I cannot reproduce this. For me, `ctx.chat` is `Chat | undefined` which is correct.
image_2024-05-06_21-24-29

**Review by roziscoding — APPROVED** [review]

**Pull request merged**
