### PR TITLE
refactor: use never record type instead of empty object

### PR DESCRIPTION
**Pull request by Nazar-Ant**
https://github.com/grammyjs/emoji/pull/19#discussion_r1239375175

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
TYSM!

**Comment by dcdunkan** [comment]
Also applicable for https://github.com/grammyjs/conversations/blob/4cf57239b92884eea67841541f9539c4e2418ef4/src/conversation.ts#L34 btw.

**Comment by Nazar-Ant** [comment]
@dcdunkan Should I fix the type there?

**Comment by dcdunkan** [comment]
@Nazar-Ant Why not, I think @KnorpelSenf would appreciate that.

**Comment by KnorpelSenf** [comment]
> @dcdunkan Should I fix the type there?

Yes please!

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Also, please fix formatting here

**Review by KnorpelSenf — APPROVED** [review]
Thanks a bunch!

**Comment by KnorpelSenf** [comment]
Consider signing your commits in the future. I will overrule now and merge anyway.

**Pull request merged**
